# Google Analytics: https://desiredpersona.com/google-analytics-jekyll/
google_analytics: UA-186063315-1
permalink: /notes/:year/:month/:day/:title
markdown: kramdown
title: Kelly Geyer
tagline: Kelly Geyer | Academic website
social:
  name: Kelly Geyer
  links:
    - https://github.com/kgeyer
    - https://www.linkedin.com/in/kelly-geyer/
    - https://gitlab.com/kgeyer
    - https://scholar.google.com/citations?user=_ldBpX0AAAAJ&hl=en
plugins:
  - jekyll-seo-tagq 

  # Site Author
author:
  name             : "Kelly Geyer"
  avatar           : "profile.png"
  bio              : ""
  location         : "Boston, MA"
  employer         :
  pubmed           : 
  googlescholar    : "https://scholar.google.com/citations?user=_ldBpX0AAAAJ&hl=en"
  email            : "klgeyer@bu.edu"
  researchgate     : 
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "https://github.com/kgeyer" 
  google_plus      :
  keybase          :
  instagram        :
  impactstory      : 
  lastfm           :
  linkedin         : "https://www.linkedin.com/in/kelly-geyer/"
  orcid            : 
  pinterest        :
  soundcloud       :
  stackoverflow    : 
  steam            :
  tumblr           :
  twitter          : 
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :
